#!/bin/bash

[ -z "$VG" ] && VG=data
[ -z "$BOOTSTRAP" ] && BOOTSTRAP=bootstrap

if [ -z "$VOL" ] && [ -z "$1" ]; then
  echo "VOL not defined." && exit 1
fi

if [ -z "$VOL" ] && [ -n "$1" ]; then
  VOL="$1"
  if [ -f "$1" ]; then source "$1"; fi
fi

